language: node_js
node_js:
  - "iojs"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
script:
  ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
